site_name: 'Dimas Jackson, PhD'
docs_dir: docs
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
site_url: https://dimasjackson.github.io/

nav:
  - Home: 'index.md'
  - Projetos: 'projetos.md'
  - Publicações: 'publicacoes.md'
  - Certificações: 'certificacoes.md'
  - Resenhas de Livros: 'resenhas_livros.md'
  - Contato: 'contato.md'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

extra_css:
  - 'styles/custom.css'

extra_javascript:
  - 'scripts/custom.js'

plugins:
  - search
  - minify