site_name: 'Dimas Jackson, PhD'
docs_dir: docs
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - header.autohide
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: material/account-tie
  language: pt
site_url: https://dimasjackson.github.io/

nav:
  - Home: 'index.md'
  - Projects: 'projetos.md'
  - Publications: 'publicacoes.md'
  - Certifications: 'certificacoes.md'
  - Book Reviews: 'resenhas_livros.md'
  - Contact: 'contato.md'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

extra_css:
  - 'styles/custom.css'

extra_javascript:
  - 'scripts/custom.js'

plugins:
  - search:
      lang:
        - pt
        - en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - social:
      cards_color:
        fill: "#4051b5"
        text: "#ffffff"
  - tags
  - git-revision-date-localized:
      type: datetime
      locale: pt